name: Build ipa(release)

#発火条件
on:
  #ソースをmainブランチにプッシュする時
  # push:
  #   branches: [main]

  workflow_dispatch:

jobs:
  build:
    #ビルド環境
    runs-on: macos-latest
    # タイムアウト時間を設定
    timeout-minutes: 15

    steps:
      #リポジトリからソースをダンロード
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Setup flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
          channel: "stable"
          cache: true

      - name: Cache pubspec dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-

      - name: Cache build runner
        uses: actions/cache@v2
        with:
          path: |
            **/.dart_tool/build
          key: build-runner-${{ hashFiles('**/asset_graph.json') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-runner-
      - name: Flutter version
        run: flutter --version

      - name: Flutter dependencies install
        #ライブラリーの導入
        run: flutter pub get

      - name: Analyze
        run: flutter analyze .
        continue-on-error: true

      - name: Build ipa
        run: |
          echo '${{ secrets.PRIVATE_KEY }}' | base64 -d > lib/private/key.dart
          flutter build ipa --release

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: release-ipa
          path: build/ios/ipa
