name: projector
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pedantic_mono: ^1.19.2
  supabase_flutter: ^0.3.3
  toggle_switch: ^2.0.1
  flutter_math_fork: ^0.6.3+1
  classroom33common:
    git:
      url: git@github.com:YumNumm/classroom33Common.git
  audioplayers: ^1.0.1

dev_dependencies:
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/category_logo/
    - assets/
  fonts:
    - family: UDDigiKyokashoN-R
      fonts:
        - asset: assets/fonts/UDDigiKyokashoN-R.ttc
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
